# from: https://github.com/linuxserver/docker-code-server
---
version: "2.1"
services:
  code-server:
    image: lscr.io/linuxserver/code-server:latest
    container_name: linuxserver-code-server
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=PST
      - PASSWORD=password #optional
      - SUDO_PASSWORD=password #optional
      - DEFAULT_WORKSPACE=/git #optional
      # Docker mods from: https://mods.linuxserver.io/?mod=code-server
      - DOCKER_MODS=linuxserver/mods:code-server-python3|linuxserver/mods:code-server-nodejs|linuxserver/mods:universal-docker
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /home/shane/appdata/config:/config
      - /home/shane/code:/git
    ports:
      - 8443:8443
    restart: unless-stopped
